language: c

sudo: required
dist: trusty

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
  - clang
  - gcc

notifications:
  email:
    - kdmfoss@gmail.com

install:
 - sudo apt-get install zlib1g-dev libgsl0-dev
 - mkdir build
 - mkdir target

script:
 - cd build
 - cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZLIB_ROOT=$HOME
 - make
 - ctest --verbose
 - make install
 - test -f ../target/bin/axe-demux
